version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-stretch #php:latest
      - image: circleci/mysql:5.7.33-ram         #8.0.20-ram
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_USER: root
          MYSQL_DATABASE: db
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_PASSWORD: ''
         
    steps:
      - checkout

      - setup_remote_docker:
         # docker_layer_caching: true not available in free plan of circle ci
      # - run:
      #     name: Start container and verify it is working
      #     command: |
      #       set -x
      #       docker-compose up -d
      #       docker run --network container:contacts \
      #         appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/contacts/test
      - run:
          name: Install MySQL driver
          command: |
            sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
            sudo docker-php-ext-install zip bcmath pdo_mysql
      - run:
          name: Install dependencies 
          command: |
            composer update
            composer install -n --prefer-dist   
      - run:
          name: copy env and generate key
          command: |
            cp .env.example .env  
            php artisan key:generate   
      - run:
          name: Migrate db 
          command: |
            php artisan migrate --env=testing --database=mysql --force --seed
      - persist_to_workspace:
      root: /root
      paths:
        - ./
      
      # - run:
      #     name: Unit tests 
      #     command: |
      #       ./vendor/bin/phpunit  
      
      # - run:
      #     name: Install linter (Plus)
      #     command: |
      #       composer require magentron/laravel-blade-lint      

      # - run:
      #     name: Run linter
      #     command: |
      #       php artisan blade:lint            

      # - run:
      #     name: Build and push Docker image
      #     command: |
      #       #docker-compose build

      #       docker build -t ahmrash/mini-crm .  #repo name must be all small letters
      #       echo $DockerHubPass | docker login -u $DockerHubUsername --password-stdin
      #       docker push ahmrash/mini-crm
  test:
    docker:
      - image: circleci/php:7.2-stretch #php:latest
      - image: circleci/mysql:5.7.33-ram         #8.0.20-ram
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_USER: root
          MYSQL_DATABASE: db
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_PASSWORD: ''
         
    steps:
     # - checkout   
      - attach_workspace:
         at: ./  
      - run:
          name: Unit tests 
          command: |
            ./vendor/bin/phpunit  

  codeHygiene:
    docker:
      - image: circleci/php:7.2-stretch #php:latest
      - image: circleci/mysql:5.7.33-ram         #8.0.20-ram
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_USER: root
          MYSQL_DATABASE: db
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_PASSWORD: ''
         
    steps:
      - checkout      
            
      - run:
          name: Install linter (Plus)
          command: |
            composer require magentron/laravel-blade-lint      

      - run:
          name: Run linter
          command: |
            php artisan blade:lint               
workflows:
  version: 2
  build-and-test:
   jobs:
      - build

      - test:
          requires:
            - build

      - codeHygiene:
          requires:
            - test
