version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest
        environment:
         
    steps:
      - checkout
           
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            docker build -t ahmad-ra/Mini-CRM/tree/circleci-project-setup .
            echo $DockerHubPass | docker login -u $DockerHubUsername --password-stdin
            docker push ahmad-ra/Mini-CRM/tree/circleci-project-setup
      